language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2" Temporary disabling Python3
install:
  - pip install -e . --use-mirrors
  - pip install MySQL-python --use-mirrors
  - pip install SQLAlchemy --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install flask --use-mirrors
  - pip install pymongo --use-mirrors
  - pip install scrypt --use-mirrors
  - pip install webtest --use-mirrors

before_script:
  - mysql -e 'create database myapp_test;' # username: "root", password: ""
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - py.test tests/test.py tests/test_scrypt.py tests/test_functional.py
    #- coverage run --source=cork tests/test_webtest_decorated.py tests/test_functional_mongodb_instance.py tests/test_functional_sqlalchemy_sqlite_in_memory.py tests/test_sqlite.py

services:
  # MySQL is started by default
  - mongodb

addons:
    postgresql: "9.3"

after_success:
  - coveralls
