language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install -e .
  - pip install MySQL-python
  - pip install SQLAlchemy
  - pip install coveralls
  - pip install flask
  - pip install psycopg2
  - pip install pymongo
  - pip install scrypt
  - pip install tox
  - pip install webtest

before_script:
  - mysql -e 'create database myapp_test;' # username: "root", password: ""
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - psql -c 'create database travis_ci_test;' -U postgres

script: tox -v

services:
  # MySQL is started by default
  - mongodb

addons:
    postgresql: "9.3"

after_success:
  - coveralls
