language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2" Temporary disabling Python3
install:
  - pip install -e . --use-mirrors
  - pip install scrypt --use-mirrors
  - pip install SQLAlchemy --use-mirrors

before_script:
  - mysql -e 'create database myapp_test;' # username: "root", password: ""
  #- mongo mydb_test --eval 'db.addUser("travis", "test");'

script: nosetests tests/test.py tests/test_functional_mysql_instance.py

services:
  # MySQL is started by default
  - mongodb

after_success:
  - coveralls
