language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2" Temporary disabling Python3
install:
  - pip install -e . --use-mirrors
  - pip install scrypt --use-mirrors
script: nosetests tests/test.py
after_success:
  - coveralls
